TatilSeyahatSitesiMvc5/Controllers/AdminYorumlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TatilSeyahatSitesiMvc5.Models;

namespace TatilSeyahatSitesiMvc5.Controllers
{
    [Authorize]
    public class AdminYorumlarController : Controller
    {
        Mvc5TatilSeyehatEntities db = new Mvc5TatilSeyehatEntities();
        // GET: AdminYorumlar
        BlogYorum by = new BlogYorum();
       
        public ActionResult Index()
        {
            var degerler = db.TBLYORUMLAR.OrderByDescending(x => x.ID).ToList();
            return View(degerler);
        }

        public ActionResult GosterGizle(int id)
        {
            var yorum = db. TBLYORUMLAR.Find(id);
            if (yorum.DURUM == false)
            {
                yorum.DURUM = true;
            }
            else
            {
                yorum.DURUM = false;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var silinecekyorum = db.TBLYORUMLAR.Find(id);

            db.TBLYORUMLAR.Remove(silinecekyorum);
            db.SaveChanges();
            TempData["sil"] = "asdf";

            return RedirectToAction("Index");
        }
        public ActionResult YorumGuncelle(TBLYORUMLAR y)
        {
            var bul = db.TBLYORUMLAR.Find(y.ID);
            bul.KullaniciAdi = y.KullaniciAdi;
            bul.Yorum = y.Yorum;
            bul.Mail = y.Mail;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YorumDetay(int id)
        {
            var bul = db.TBLYORUMLAR.Find(id);
            return View("YorumDetay", bul);
        }





        //------------------------------------------------------------------------//
        public ActionResult OtelYorum()
        {
            var degerler = db.TBLOTELYORUM.OrderByDescending(x => x.ID).ToList();
            return View(degerler);
        }

        public ActionResult GosterGizleOtel(int id)
        {
            var yorum = db.TBLOTELYORUM.Find(id);
            if (yorum.DURUM == false)
            {
                yorum.DURUM = true;
            }
            else
            {
                yorum.DURUM = false;
            }
            db.SaveChanges();
            return RedirectToAction("OtelYorum");
        }

        public ActionResult SilOtel(int id)
        {
            var silinecekyorum = db.TBLOTELYORUM.Find(id);

            db.TBLOTELYORUM.Remove(silinecekyorum);
            db.SaveChanges();
            TempData["sil"] = "asdf";

            return RedirectToAction("OtelYorum");
        }
        public ActionResult YorumGuncelleOtel(TBLOTELYORUM y)
        {
            var bul = db.TBLOTELYORUM.Find(y.ID);
            bul.KullaniciAdi = y.KullaniciAdi;
            bul.Yorum = y.Yorum;
            bul.Mail = y.Mail;
            db.SaveChanges();
            return RedirectToAction("OtelYorum");
        }
        public ActionResult YorumDetayOtel(int id)
        {
            var bul = db.TBLOTELYORUM.Find(id);
            return View("YorumDetayOtel", bul);
        }







        //-----------------------------------------------------------------------------------//
        public ActionResult RestaurantYorum()
        {
            var degerler = db.TBLRESTAURANTYORUM.OrderByDescending(x => x.ID).ToList();
            return View(degerler);
        }

        public ActionResult GosterGizleRestaurant(int id)
        {
            var yorum = db.TBLRESTAURANTYORUM.Find(id);
            if (yorum.DURUM == false)
            {
                yorum.DURUM = true;
            }
            else
            {
                yorum.DURUM = false;
            }
            db.SaveChanges();
            return RedirectToAction("RestaurantYorum");
        }

        public ActionResult SilRestaurant(int id)
        {
            var silinecekyorum = db.TBLRESTAURANTYORUM.Find(id);

            db.TBLRESTAURANTYORUM.Remove(silinecekyorum);
            db.SaveChanges();
            TempData["sil"] = "asdf";

            return RedirectToAction("RestaurantYorum");
        }
        public ActionResult YorumGuncelleRestaurant(TBLRESTAURANTYORUM y)
        {
            var bul = db.TBLRESTAURANTYORUM.Find(y.ID);
            bul.KullaniciAdi = y.KullaniciAdi;
            bul.Yorum = y.Yorum;
            bul.Mail = y.Mail;
            db.SaveChanges();
            return RedirectToAction("OtelYorum");
        }
        public ActionResult YorumDetayRestaurant(int id)
        {
            var bul = db.TBLRESTAURANTYORUM.Find(id);
            return View("YorumDetayRestaurant", bul);
        }








        //-----------------------------------------------------------------------------------
        public ActionResult MuzelerYorum()
        {
            var degerler = db.TBLMUZEYORUM.OrderByDescending(x => x.ID).ToList();
            return View(degerler);
        }

        public ActionResult GosterGizleMuzeler(int id)
        {
            var yorum = db.TBLMUZEYORUM.Find(id);
            if (yorum.DURUM == false)
            {
                yorum.DURUM = true;
            }
            else
            {
                yorum.DURUM = false;
            }
            db.SaveChanges();
            return RedirectToAction("MuzelerYorum");
        }

        public ActionResult SilMuzeler(int id)
        {
            var silinecekyorum = db.TBLMUZEYORUM.Find(id);

            db.TBLMUZEYORUM.Remove(silinecekyorum);
            db.SaveChanges();
            TempData["sil"] = "asdf";

            return RedirectToAction("MuzelerYorum");
        }
        public ActionResult YorumGuncelleMuzeler(TBLMUZEYORUM y)
        {
            var bul = db.TBLMUZEYORUM.Find(y.ID);
            bul.KullaniciAdi = y.KullaniciAdi;
            bul.Yorum = y.Yorum;
            bul.Mail = y.Mail;
            db.SaveChanges();
            return RedirectToAction("MuzelerYorum");
        }
        public ActionResult YorumDetayMuzeler(int id)
        {
            var bul = db.TBLMUZEYORUM.Find(id);
            return View("YorumDetayMuzeler", bul);
        }
    }
}

TatilSeyahatSitesiMvc5/Views/AdminYorumlar/Index.cshtml
@using TatilSeyahatSitesiMvc5.Models
@model List<TBLYORUMLAR>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{ string isim = "aa";}
<h2 style="display:flex; justify-content:center;">Blog Yorum Sayfası</h2>
<br />
<table class="table table-bordered">
    <tr>
        <td>ID</td>
        <td>BLOG</td>
        <td>Kullanıcı Adı</td>
        <td>TARIH</td>
        <td>DURUM</td>
        <td>GÜNCELLE</td>
        <td>SİL</td>
        <td>DETAYLAR</td>
    </tr>
    @foreach (var x in Model)
    {
        isim = isim + x.ID;
        <tr>
            
            <td>@x.ID</td>
            <td>@if (x.TBLBLOG.Baslik.Length < 20)
            {
                @x.TBLBLOG.Baslik
                }
            else
            {
                @x.TBLBLOG.Baslik.Substring(0, 20)
            }
            </td>
            <td>@x.KullaniciAdi</td>
            <td>@x.Tarih.Value.ToString("dd.mm.yyyy")</td>
            <td>
                @if (x.DURUM == false)
                {
                    <a href="/AdminYorumlar/GosterGizle/@x.ID"
                       class="btn btn-warning btn-sm">Görünür Yap</a>
                }
                else
                {
                    <a href="/AdminYorumlar/GosterGizle/@x.ID"
                       class="btn btn-success btn-sm">Gizle</a>
                }
            </td>
            <td>
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#@isim">
                    Blog Yorum Güncelleme
                </button>

                <div class="modal fade" id="@isim" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">@x.KullaniciAdi   Yorumunu Güncelle</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                @using (Html.BeginForm("YorumGuncelle", "AdminYorumlar", FormMethod.Post))
                                {
                                    <div class="form-group">
                                        ID
                                        <input type="text"
                                               name="ID"
                                               value="@x.ID"
                                               class="form-control"
                                               style="border:1px solid red" />

                                        Kullanıcı Adı
                                        <input type="text"
                                               name="KullaniciAdi"
                                               value="@x.KullaniciAdi"
                                               class="form-control"
                                               style="border:1px solid red" />
                                        Mail
                                        <input type="text"
                                               rows="5"
                                               name="Mail"
                                               value="@x.Mail"
                                               class="form-control"
                                               style="border:1px solid red" />
                                        Yorum
                                        <input type="text"
                                               rows="5"
                                               name="YORUM"
                                               value="@x.Yorum"
                                               class="form-control"
                                               style="border:1px solid red" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">VAZGEÇ</button>
                                        <button class="btn btn-success">Değişiklikleri Kaydet </button>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td>
                @Html.ActionLink("Sil", "Sil", new { id = x.ID }, new { @class = "btn btn-danger", onclick = "return confirm" + " ('Bu kaydı silmek istediğinize emin misiniz?');" })
            </td>
            <td><a class="btn btn-info" href="/AdminYorumlar/YorumDetay/@x.ID">Detay</a></td>
        </tr>
    }
</table>

@if (TempData["ekle"] != null)
{
    <script>

        toastr["warning"]("PERSONEL EKLENDİ")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

@if (TempData["guncelle"] != null)
{
    <script>

        toastr["warning"]("PERSONEL GÜNCELLENDİ")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

TatilSeyahatSitesiMvc5/Views/AdminYorumlar/MuzelerYorum.cshtml
@using TatilSeyahatSitesiMvc5.Models
@model List<TBLMUZEYORUM>
@{
    ViewBag.Title = "MuzelerYorum";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@{ string isim = "aa";}
<h2 style="display:flex; justify-content:center;">Gezilerim Yorum Sayfası</h2>
<br />
<table class="table table-bordered">
    <tr>
        <td>ID</td>
        <td>GEZİLEİM ADLARI</td>
        <td>KULLANICI ADI</td>
        <td>TARIH</td>
        <td>DURUM</td>
        <td>GÜNCELLE</td>
        <td>SİL</td>
        <td>DETAYLAR</td>
    </tr>
    @foreach (var x in Model)
    {
        isim = isim + x.ID;
        <tr>
            <td>@x.ID</td>
            <td>@x.TBLMUZELER.Baslik.Substring(0, 20)</td>
            <td>@x.KullaniciAdi</td>
            <td>@x.Tarih.Value.ToString("dd.mm.yyyy")</td>
            <td>
                @if (x.DURUM == false)
                {
                    <a href="/AdminYorumlar/GosterGizleMuzeler/@x.ID"
                       class="btn btn-warning btn-sm">Görünür Yap</a>
                }
                else
                {
                    <a href="/AdminYorumlar/GosterGizleMuzeler/@x.ID"
                       class="btn btn-success btn-sm">Gizle</a>
                }
            </td>
            <td>
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#@isim">
                    Gezilerim Yorum Güncelleme
                </button>

                <div class="modal fade" id="@isim" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">@x.KullaniciAdi   Yorumunu Güncelle</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                @using (Html.BeginForm("YorumGuncelleMuzeler", "AdminYorumlar", FormMethod.Post))
                                {
                                    <div class="form-group">
                                        ID
                                        <input type="text"
                                               name="ID"
                                               value="@x.ID"
                                               class="form-control"
                                               style="border:1px solid red" />

                                        Kullanıcı Adı
                                        <input type="text"
                                               name="KullaniciAdi"
                                               value="@x.KullaniciAdi"
                                               class="form-control"
                                               style="border:1px solid red" />
                                        Mail
                                        <input type="text"
                                               rows="5"
                                               name="Mail"
                                               value="@x.Mail"
                                               class="form-control"
                                               style="border:1px solid red" />
                                        Yorum
                                        <input type="text"
                                               rows="5"
                                               name="YORUM"
                                               value="@x.Yorum"
                                               class="form-control"
                                               style="border:1px solid red" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">VAZGEÇ</button>
                                        <button class="btn btn-success">Değişiklikleri Kaydet </button>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td>
                @Html.ActionLink("SilMuzeler", "Sil", new { id = x.ID }, new { @class = "btn btn-danger", onclick = "return confirm" + " ('Bu kaydı silmek istediğinize emin misiniz?');" })
            </td>
            <td><a class="btn btn-info" href="/AdminYorumlar/YorumDetayMuzeler/@x.ID">Detay</a></td>
        </tr>
    }
</table>

@if (TempData["ekle"] != null)
{
    <script>

        toastr["warning"]("PERSONEL EKLENDİ")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

@if (TempData["guncelle"] != null)
{
    <script>

        toastr["warning"]("PERSONEL GÜNCELLENDİ")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

TatilSeyahatSitesiMvc5/Views/AdminYorumlar/OtelYorum.cshtml
@using TatilSeyahatSitesiMvc5.Models
@model List<TBLOTELYORUM>
@{
    ViewBag.Title = "OtelYorum";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{ string isim = "aa";}
<h2 style="display:flex; justify-content:center;">Otel Yorum Sayfası</h2>
<br />
<table class="table table-bordered">
    <tr>
        <td>ID</td>
        <td>OTEL ADLARI</td>
        <td>Kullanıcı Adı</td>
        <td>TARIH</td>
        <td>DURUM</td>
        <td>GÜNCELLE</td>
        <td>SİL</td>
        <td>DETAYLAR</td>
    </tr>
    @foreach (var x in Model)
    {
        isim = isim + x.ID;
        <tr>
            <td>@x.ID</td>
            <td>@x.TBLOTELLER.Baslik.Substring(0,20)</td>
            <td>@x.KullaniciAdi</td>
            <td>@x.Tarih.Value.ToString("dd.mm.yyyy")</td>
            <td>
                @if (x.DURUM == false)
                {
                    <a href="/AdminYorumlar/GosterGizleOtel/@x.ID"
                       class="btn btn-warning btn-sm">Görünür Yap</a>
                }
                else
                {
                    <a href="/AdminYorumlar/GosterGizleOtel/@x.ID"
                       class="btn btn-success btn-sm">Gizle</a>
                }
            </td>
            <td>
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#@isim">
                    Otel Yorum Güncelleme
                </button>

                <div class="modal fade" id="@isim" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">@x.KullaniciAdi   Yorumunu Güncelle</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                @using (Html.BeginForm("YorumGuncelleOtel", "AdminYorumlar", FormMethod.Post))
                                {
                                    <div class="form-group">
                                        ID
                                        <input type="text"
                                               name="ID"
                                               value="@x.ID"
                                               class="form-control"
                                               style="border:1px solid red" />

                                        Kullanıcı Adı
                                        <input type="text"
                                               name="KullaniciAdi"
                                               value="@x.KullaniciAdi"
                                               class="form-control"
                                               style="border:1px solid red" />
                                        Mail
                                        <input type="text"
                                               rows="5"
                                               name="Mail"
                                               value="@x.Mail"
                                               class="form-control"
                                               style="border:1px solid red" />
                                        Yorum
                                        <input type="text"
                                               rows="5"
                                               name="YORUM"
                                               value="@x.Yorum"
                                               class="form-control"
                                               style="border:1px solid red" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">VAZGEÇ</button>
                                        <button class="btn btn-success">Değişiklikleri Kaydet </button>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td>
                @Html.ActionLink("SilOtel", "Sil", new { id = x.ID }, new { @class = "btn btn-danger", onclick = "return confirm" + " ('Bu kaydı silmek istediğinize emin misiniz?');" })
            </td>
            <td><a class="btn btn-info" href="/AdminYorumlar/YorumDetayOtel/@x.ID">Detay</a></td>
        </tr>
    }
</table>

@if (TempData["ekle"] != null)
{
    <script>

        toastr["warning"]("PERSONEL EKLENDİ")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

@if (TempData["guncelle"] != null)
{
    <script>

        toastr["warning"]("PERSONEL GÜNCELLENDİ")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

TatilSeyahatSitesiMvc5/Views/AdminYorumlar/RestaurantYorum.cshtml
@using TatilSeyahatSitesiMvc5.Models
@model List<TBLRESTAURANTYORUM>
@{
    ViewBag.Title = "RestaurantYorum";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@{ string isim = "aa";}
<h2 style="display:flex; justify-content:center;">Restaurant Yorum Sayfası</h2>
<br />
<table class="table table-bordered">
    <tr>
        <td>ID</td>
        <td>RESTAURANT ADLARI</td>
        <td>KULLANICI ADI</td>
        <td>TARIH</td>
        <td>DURUM</td>
        <td>GÜNCELLE</td>
        <td>SİL</td>
        <td>DETAYLAR</td>
    </tr>
    @foreach (var x in Model)
    {
        isim = isim + x.ID;
        <tr>
            <td>@x.ID</td>
            <td>@x.TBLRESTAURANT.Baslik.Substring(0, 20)</td>
            <td>@x.KullaniciAdi</td>
            <td>@x.Tarih.Value.ToString("dd.mm.yyyy")</td>
            <td>
                @if (x.DURUM == false)
                {
                    <a href="/AdminYorumlar/GosterGizleRestaurant/@x.ID"
                       class="btn btn-warning btn-sm">Görünür Yap</a>
                }
                else
                {
                    <a href="/AdminYorumlar/GosterGizleRestaurant/@x.ID"
                       class="btn btn-success btn-sm">Gizle</a>
                }
            </td>
            <td>
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#@isim">
                    Restaurant Yorum Güncelleme
                </button>

                <div class="modal fade" id="@isim" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">@x.KullaniciAdi   Yorumunu Güncelle</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                @using (Html.BeginForm("YorumGuncelleRestaurant", "AdminYorumlar", FormMethod.Post))
                                {
                                    <div class="form-group">
                                        ID
                                        <input type="text"
                                               name="ID"
                                               value="@x.ID"
                                               class="form-control"
                                               style="border:1px solid red" />

                                        Kullanıcı Adı
                                        <input type="text"
                                               name="KullaniciAdi"
                                               value="@x.KullaniciAdi"
                                               class="form-control"
                                               style="border:1px solid red" />
                                        Mail
                                        <input type="text"
                                               rows="5"
                                               name="Mail"
                                               value="@x.Mail"
                                               class="form-control"
                                               style="border:1px solid red" />
                                        Yorum
                                        <input type="text"
                                               rows="5"
                                               name="YORUM"
                                               value="@x.Yorum"
                                               class="form-control"
                                               style="border:1px solid red" />
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">VAZGEÇ</button>
                                        <button class="btn btn-success">Değişiklikleri Kaydet </button>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td>
                @Html.ActionLink("SilRestaurant", "Sil", new { id = x.ID }, new { @class = "btn btn-danger", onclick = "return confirm" + " ('Bu kaydı silmek istediğinize emin misiniz?');" })
            </td>
            <td><a class="btn btn-info" href="/AdminYorumlar/YorumDetayRestaurant/@x.ID">Detay</a></td>
        </tr>
    }
</table>

@if (TempData["ekle"] != null)
{
    <script>

        toastr["warning"]("PERSONEL EKLENDİ")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

@if (TempData["guncelle"] != null)
{
    <script>

        toastr["warning"]("PERSONEL GÜNCELLENDİ")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}