TatilSeyahatSitesiMvc5/Controllers/OtellerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TatilSeyahatSitesiMvc5.Models;

namespace TatilSeyahatSitesiMvc5.Controllers
{
    public class OtellerController : Controller
    {
        Mvc5TatilSeyehatEntities db = new Mvc5TatilSeyehatEntities();
        // GET: Oteller
        BlogYorum by=new BlogYorum();
        public ActionResult Index() {
            by.oteller = db.TBLOTELLER.ToList();
            by.oteller2 = db.TBLOTELLER.OrderByDescending(x => x.ID).Take(5).ToList();
            by.otelyorumlar = db.TBLOTELYORUM.Where(x=>x.DURUM==true).OrderByDescending(x => x.ID).Take(5).ToList();
            return View(by);
        }
        public ActionResult OtelDetay(int id)
        {
            by.oteller = db.TBLOTELLER.Where(x => x.ID == id).ToList();
            by.otelyorumlar = db.TBLOTELYORUM.Where(x => x.OTELID == id && x.DURUM==true).ToList();
            by.oteller2 = db.TBLOTELLER.OrderByDescending(x => x.ID).Take(5).ToList();
            by.otelyorumlar2 = db.TBLOTELYORUM.Where(x=>x.DURUM==true).OrderByDescending(x => x.ID).Take(5).ToList();
            return View(by);
        }


        public PartialViewResult YorumYap(int id)
        {
            ViewBag.deger = id;
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult YorumYap(TBLOTELYORUM y)
        {
            TBLOTELYORUM yeni = new TBLOTELYORUM();
            yeni.KullaniciAdi = y.KullaniciAdi;
            yeni.Yorum = y.Yorum;
            yeni.Mail = y.Mail;
            yeni.OTELID = y.OTELID;
            yeni.DURUM = false;
            yeni.Tarih = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            db.TBLOTELYORUM.Add(yeni);
            db.SaveChanges();
            Response.Redirect("/Oteller/OtelDetay/" + y.OTELID);
            return PartialView();
        }
    }
}

TatilSeyahatSitesiMvc5/Views/Oteller/Index.cshtml
@model TatilSeyahatSitesiMvc5.Models.BlogYorum
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AnasayfaLayout.cshtml";
}

<style>
    .container {
        display: flex;
        flex-direction: row;
        margin-top: 30px;
    }

        .container .sutun {
            width: 65%;
        }

        .container .sutun2 {
            width: 35%;
        }

        .container .sutun .blogs {
            margin-bottom: 50px;
        }

            .container .sutun .blogs .img img {
                width: 640px;
                height: 427px;
                border-radius: 8px;
                margin-bottom: 10px;
            }

            .container .sutun .blogs .details {
                border: 1px solid;
                width: 640px;
                padding: 10px 20px 10px 20px;
                border-radius: 8px;
            }

    .sutun2 .sonblog {
        display: flex;
        flex-direction: column;
    }

    .sutun2 .sonyorum {
        display: flex;
        flex-direction: column;
    }


    .bosluk {
        margin: 0px 0px 10px 0px;
    }

    .text {
        text-decoration: none;
    }
</style>
<div style="width: 1170px;" class="container">
    <div class="sutun">
        @foreach (var x in Model.oteller)
        {
            <div class="blogs">
                <div class="img">
                    <img src="~/IMG/@x.OtellerImage">
                </div>
                <div class="details">
                    <h3>@Html.Raw(x.Baslik)</h3>
                    <h6>@x.Tarih.Value.ToString("dd.MM.yyyy")/comment 27</h6>
                    <p>
                        @Html.Raw(x.Aciklama.Substring(0, 200))
                        <a href="/Muzeler/MuzelerDetay/@x.ID">Devamını Oku</a>
                </div>
            </div>
        }
    </div>
    <div class="sutun2">
        <h4>Son Kaldığım Oteller</h4>
        <div class="sonblog">
            @foreach (var y in Model.oteller2)
            {
                <a class="text" href="/Oteller/OtelDetay/@y.ID">@Html.Raw(y.Baslik)</a>
                <hr class="bosluk">
            }


        </div>
        <br />
        <br />
        <br />
        <h4>Son Yorumlar</h4>
        <div class="sonyorum">
            @foreach (var z in Model.otelyorumlar)
            {
                <a class="text" href="/Oteller/OtelDetay/@z.OTELID">
                    @z.KullaniciAdi on

                                @if (z.Yorum.Length < 20)
                                {
                                    @z.Yorum
                                }
                                else
                                {
                                    @z.Yorum.Substring(0, 20)
                                }
                            </a>
                <hr class="bosluk">
            }


        </div>
    </div>
</div>

TatilSeyahatSitesiMvc5/Views/Oteller/OtelDetay.cshtml
@model TatilSeyahatSitesiMvc5.Models.BlogYorum
@{
    ViewBag.Title = "OtelDetay";
    Layout = "~/Views/Shared/_AnasayfaLayout.cshtml";
}
<style>
    .container {
        display: flex;
        flex-direction: row;
        margin-top: 30px;
    }

        .container .sutun {
            width: 65%;
        }

        .container .sutun2 {
            width: 35%;
        }

        .container .sutun .blogs .img img {
            width: 640px;
            height: 427px;
            border-radius: 8px;
            margin-bottom: 20px;
        }

        .container .sutun .blogs .details {
            padding: 0px 0px 0px 20px;
            width: 640px;
            border-radius: 8px;
        }

    .sutun2 .sonblog {
        display: flex;
        flex-direction: column;
    }

    .sutun2 .sonyorum {
        display: flex;
        flex-direction: column;
    }

    .sutun2 h4 {
    }

    .bosluk {
        margin: 0px 0px 10px 0px;
    }


    .text {
        text-decoration: none;
    }

    .container .sutun .yorums {
        border: 1px solid;
        display: flex;
        width: 640px;
        margin-top: 10px;
        border-radius: 8px;
    }

        .container .sutun .yorums .img img {
            width: 70px;
            height: auto;
            margin-top: 5px;
        }
</style>

<div style="width: 1170px;" class="container">
    <div class="sutun">
        @foreach (var x in Model.oteller)
        {
            <div class="blogs">
                <div class="img">
                    <img src="~/IMG/@x.OtellerImage">
                </div>
                <div class="details">
                    <h3>@x.Baslik</h3>
                    <h6>@x.Tarih.Value.ToString("dd.MM.yyyy")</h6>
                    <p>@x.Aciklama</p>

                </div>
            </div>
        }
        <h4 style="margin-top:40px;">Yorumlar / 27</h4>
        @foreach (var y in Model.otelyorumlar)
        {
            <div class="yorums">
                <div class="img">
                    <img src="~/IMG/user_1077114.png">
                </div>
                <div class="details">
                    <h4>@y.KullaniciAdi</h4>
                    <h6 style="margin-top:-10px;">@y.Tarih</h6>
                    <p>@y.Yorum</p>
                </div>
            </div>
        }
        @Html.Action("YorumYap", "Oteller")
    </div>
    <div class="sutun2">
        <h4>Son Kaldığım Oteller</h4>
        <div class="sonblog">
            @foreach (var z in Model.oteller2)
            {
                <a class="text" href="~/Oteller/OtelDetay/@z.ID">@z.Baslik</a>
                <hr class="bosluk">
            }

        </div>
        <h4>Son Yorumlar</h4>
        <div class="sonyorum">
            @foreach (var a in Model.otelyorumlar2)
            {
                <a class="text" href="/Oteller/OtelDetay/@a.OTELID">
                    @a.KullaniciAdi on
                    @if (a.Yorum.Length < 20)
                    {
                        @a.Yorum
                    }
                    else
                    {
                        @a.Yorum.Substring(0, 20)
                    }
                </a>
                <hr class="bosluk">
            }
        </div>
    </div>
</div>

TatilSeyahatSitesiMvc5/Views/Oteller/YorumYap.cshtml
@model TatilSeyahatSitesiMvc5.Models.TBLOTELYORUM


<h4 style="margin-top:20px;">Yorum Yap</h4>
<form style="display:flex; flex-direction:column;width:640px;" method="post">
    <input type="hidden" placeholder="ID" name="OTELID" value="@ViewBag.deger" required />
    <input style="padding:5px;margin-bottom:5px;" type="text" placeholder="Kullanıcı Adı" name="KullaniciAdi" required />
    <input style="padding: 5px; margin-bottom: 5px;" type="text" placeholder="Mail" name="Mail" required />
    <textarea style="padding: 5px; height: 100px; margin-bottom: 5px; " placeholder="Mesaj Yazın" name="Yorum"></textarea>
    <button style="background-color: #a2365a; color:white; width:100px;" class="btn" type="submit">Gönder</button>
</form>