TatilSeyahatSitesiMvc5/Controllers/AdminUyelerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using TatilSeyahatSitesiMvc5.Models;

namespace TatilSeyahatSitesiMvc5.Controllers
{
    public class AdminUyelerController : Controller
    {
        // GET: AdminUyeler
        Mvc5TatilSeyehatEntities db = new Mvc5TatilSeyehatEntities();
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(TBLADMIN ekleme)
        {
            var degerler = db.TBLADMIN.Where(x => x.KullanıcıAdı == ekleme.KullanıcıAdı && x.Sifre == ekleme.Sifre).FirstOrDefault();
            if (degerler==null) 
            { 
             TBLADMIN blog = new TBLADMIN();
             blog.KullanıcıAdı = ekleme.KullanıcıAdı;
             blog.Sifre = ekleme.Sifre;
             db.TBLADMIN.Add(blog);
             db.SaveChanges();
             return RedirectToAction("Index");
            }
            else
            {
                ViewBag.uyarı = "Bu kullanıcı zaten var";
            }
            return View();
        }



        public ActionResult Uyeler()
        {
            var degerler = db.TBLADMIN.ToList();
            return View(degerler);
        }
        public ActionResult GosterGizle(int id)
        {
            var yorum = db.TBLADMIN.Find(id);
            if (yorum.Yetki != null)
            {
                yorum.Yetki = null;
            }
            else
            {
                yorum.Yetki = true;
            }
            db.SaveChanges();
            return RedirectToAction("Uyeler");
        }

        public ActionResult Sil(int id)
        {
            var silinecekyorum = db.TBLADMIN.Find(id);
            db.TBLADMIN.Remove(silinecekyorum);
            db.SaveChanges();
            TempData["sil"] = "asdf";
            return RedirectToAction("Uyeler");
        }
    }
}

TatilSeyahatSitesiMvc5/Views/AdminUyeler/Index.cshtml
@{
    Layout = null;
}

<html lang="en">
<head>
    <title>TD AP Giriş</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/Login/css/style.css">

</head>
<body class="img js-fullheight" style="background-image: url(../Login/images/bg.jpg);">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">KAYIT BÖLÜMÜ</h2>
                </div>
            </div>
            @if (ViewBag.uyarı != null)
            {
                <h2 style="text-align:center;"> @ViewBag.uyarı</h2>
            }
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        @using (Html.BeginForm("Index", "AdminUyeler", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <form action="#" class="signin-form" method="post">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="KullanıcıAdı" placeholder="Kullanıcı Adı" required>
                                </div>
                                <div class="form-group">
                                    <input id="password-field" type="password" name="Sifre" class="form-control" placeholder="Sifre" required>
                                    <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="form-control btn btn-primary submit px-3">Kayıt Ol</button>
                                </div>
                            </form>
                        }
                        <a style="background-color:blanchedalmond; color:black;" class="btn" href="/Login/Login">Giriş Sayfasına Dön</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/Login/js/jquery.min.js"></script>
    <script src="~/Login/js/popper.js"></script>
    <script src="~/Login/js/bootstrap.min.js"></script>
    <script src="~/Login/js/main.js"></script>

</body>
</html>



@if (TempData["ekle"] != null)
{
    <script>

        toastr["warning"]("Başarıyla Kayıt oldu")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

TatilSeyahatSitesiMvc5/Views/AdminUyeler/Uyeler.cshtml
@using TatilSeyahatSitesiMvc5.Models
@model List<TBLADMIN>
@{
    ViewBag.Title = "Uyeler";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{ string isim = "aa";}
<h2 style="display:flex; justify-content:center;">Admin Yetkilendirme Yeri</h2>
<br />
<table class="table table-bordered">
    <tr>
        <td>ID</td>
        <td>Kullanıcı Adı</td>
        <td>Yetki</td>
        <td>SİL</td>
    </tr>
    @foreach (var x in Model)
    {
        isim = isim + x.ID;
        <tr>

            <td>@x.ID</td>
            
        <td>@x.KullanıcıAdı</td>
        <td>
            @if (x.Yetki != null)
            {
                <a href="/AdminUyeler/GosterGizle/@x.ID"
                   class="btn btn-warning btn-sm">Yetkisini Al</a>
            }
            else
            {
                <a href="/AdminUyeler/GosterGizle/@x.ID"
                   class="btn btn-success btn-sm">Yetkilendir</a>
            }
        </td>
        <td>
            @Html.ActionLink("Sil", "Sil", new { id = x.ID }, new { @class = "btn btn-danger", onclick = "return confirm" + " ('Bu kaydı silmek istediğinize emin misiniz?');" })
        </td>
    </tr>
}
</table>

@if (TempData["ekle"] != null)
{
    <script>

        toastr["warning"]("PERSONEL EKLENDİ")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

@if (TempData["guncelle"] != null)
{
    <script>

        toastr["warning"]("PERSONEL GÜNCELLENDİ")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}